### PR TITLE
Correct compatibility

### PR DESCRIPTION
**Pull request by tinect**
Isn't it this compatibility?
minVersion="5.2.0" maxVersion="5.5.0"

### CODE REVIEW

**Comment by shyim** [comment]
maxVersion does not really make sense, cause most customers updates with ioncubed plugins and then they remove it

**Comment by tinect** [comment]
okay, sounds legit ;-) but minversion is 5.2, isn't it?

**Comment by larsbo** [comment]
I think so 😄  5.3 works fine and didn't know why 5.2 shouldn't. That's why I omitted the entry (which means 5.2)

**Comment by tinect** [comment]
@larsbo That's why I was confused :-) PluginUploader needs this tag, so shyim set it in this plugin. But I think 5.4 is too high, cause there shopware can be updated to 5.5 from 5.0.

**Pull request merged**
